### ISSUE TITLE
Drink time! 🍺 #2

### ISSUE THREAD

**Issue by marijo-blazevic** [AlgebraStudentCollab/START-HERE#16]
Drugo izdanje team buildinga u pivnici :)

Lokacija ista, vrijeme 17.11 @ 20:15 nakon predavanja

@tsucevic 
@lcabraja 
@BornaFikajz 
@JosipKustan 
@mkovac6 
@psporcic

**Comment by mkovac6** [comment]
Danas je 16.11, mislis 17.11?

**Comment by marijo-blazevic** [comment]
Da fuck, fixed

**Comment by JosipKustan** [comment]
Yes

**Comment by psporcic** [comment]
Yes 🍻
