### ISSUE TITLE
Drink time! 🍺

### ISSUE THREAD

**Issue by JosipKustan** [AlgebraStudentCollab/START-HERE#7]
Sljedeći tjedan da sjednemo na piće? Mozda nakon predavanja srijeda ili četvrtak?

**Comment by psporcic** [comment]
Može!☺️ Meni isto više odgovara srijeda.

**Comment by tsucevic** [comment]
Srijeda it is, napravi nam task u github projects :)

**Comment by marijo-blazevic** [comment]
ekipa sutra deal stoji? Malo mi je daleko Garden B. ajmo negdje blize oko algebre (s biciklom sam) ?

**Comment by BornaFikajz** [comment]
Meni isto paše nakon predavanja. Možemo sjesti negdje u blizini ala Pivana ili Linea

**Comment by JosipKustan** [comment]
I agree. Pivana then?

**Comment by psporcic** [comment]
Onda danas u Pivani u 20:30 (možda i ranije ako nas pusti s predavanja) 🍻😊 vidimo se

**Comment by JosipKustan** [comment]
Closing the discussion. Pivana nakon predavanja
